### ISSUE TITLE
netstandard2.0 : StringComparison does not work in generated class

### ISSUE THREAD

**Issue by MartinsPlume** [andrewlock/NetEscapades.EnumGenerators#52]
It is missing reference in the generated class, where System.StringComparison is called.

**Comment by andrewlock** [comment]
Hi, I can't seem to replicate the issue, can you provide more details please? 🤔

I added an integration test in #53 that explicitly builds for netstandard2.0 and it seems to work fine

**Comment by Feroks** [comment]
After checking code with @MartinsPlume, it appears that problem is not related to .NET Standard.
Issue with `System.StringComparison` occurs, if you have folder called `System` in your project. Generated class attempts to resolve `StringComparison` from it instead of using actual `System` namespace.
I have created [repository ](https://github.com/Feroks/NetEscapades.EnumGenerators.SystemNamespaceIssue)that replicates this issue. I am not sure if anything can be done about in your library, so feel free to close this issue.

**Comment by andrewlock** [comment]
Ah I see. I've created a PR that adds the `global::` prefix to try to solve the issue. I'll push up a new version shortly, I'd appreciate if you could give it a try and see if solves your issue! 🙂

**Comment by Feroks** [comment]
Totally forgot that `global::` exists 😅 
Tried latest package, it works perfectly. Thank you!
