### ISSUE TITLE
Generate PatternMatch

### ISSUE THREAD

**Issue by BashkaMen** [andrewlock/NetEscapades.EnumGenerators#76]
```
public enum Status 
{
    Created,
    InWork,
    Completed,
    Canceled
}
```
need generate switch operator wrapper for handle all variants, and use it in mappers
such a function will break mappers when i add new enum item

```
public static class StatusMapper
{
    public static T Match<T>(this Status x, Func<T> onCreated, Func<T> inWork, ....) => x switch 
    {
         Created => onCreated(),
         ....
        _ => thow new UnreachException(),
    }
}
```

**Comment by NotAsea** [comment]
I feel your proposal is geared toward Discriminated Union, and out of scope for this library. The author intention is define faster implementation for Enum than the one built-in, hence he even experimented Interceptor to complete overwrite Enum builtin function but failed due to preview feature. Your requested feature can be achieved by DU library like OneOf or source gen one like Dunet

**Comment by andrewlock** [comment]
Thanks for the suggestion, but as NotAsea indicated, I think that's out of scope for this library (which aims to be a more-performant version of the built-in functions), so going to close this as out of scope
